private - contents
swiftIconContents
	"Private - Method generated with the content of the file File @ swift.png"

	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAolBMVEVHcEz/bQD//////fz/bQD/bADmShn/bQD/bQDtUxL++PbmTBzzqJD/dA3nTx/+awH/4MjsUhP/ehb+exzyWw3oWi3rb0j/zaf/u4j/dhD/cAX8yKrtXiT/bgH5vqT/eRXugV//lUXynoP8vZb5rofyXxT/oVv/lkj/+PT/giTwkHHyn4Xuhmb0rpj1tJ//o1/nUCH2wK/1tqL1t6PvjW774trbsUGsAAAACnRSTlMA////m5n//JrZM19/sQAAAHxJREFUGNONz0kWgkAMRVESNKVlgdiLCqjY9w3sf2tEDMWUN7yDnB/HaVCXuDFwqlUCle2jnwj4E6LebsEiMF3fiExaA12/91fmngUGLB+dv/Ep0F/xhQciHgRgFG8vRiPOK4Dh0kU8zQILAMnmGIInoMD2H9axotpNXi0Ay/sGtc5AHIgAAAAASUVORK5CYII='